### ISSUE TITLE
Incorrect login info for initial screen in VirtualBox

### ISSUE THREAD

**Issue by archivist-liz** [intranda/goobi-to-go#1]
When I try to run Goobi-to-Go in VirtualBox, I cannot get past the login request. Neither testadmin test nor goobi goobi work. I am providing a screenshot. What would be the correct login info? Or is there something wrong with my installation? (I also could not get to the Goobi to Go viewer or workflow via my localhost.)
![virtualbox_goobi-to-go_default_1550787902714_48549_21_02_2019_23_43_44](https://user-images.githubusercontent.com/30337009/53208113-f4382e80-3635-11e9-8308-7fd5e71182b0.png)

**Comment by janvonde** [comment]
Hi @archivist-liz,

welcome at Goobi! 


This Goobi-to-go variant is deprecated. We stopped developing and supporting it in favor of a new variant. You can find the new version here:
* https://www.intranda.com/en/digiverso/goobi/goobi-to-go/

I will change the README.md in a few moments. 

In case you have further questions feel yourself very much invited to ask your questions for example at the Goobi community forum. You can find it at https://community.goobi.io. 


Have a good start into the week,

Jan :smile: 

P.S. Your problem here is, that you try to login at the Linux shell, but not at the web UI. It should be available at http://localhost:8080/goobi/.
